
package org.lamisplus.modules.ndr.schema;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.05.04 at 08:58:02 AM WAT
//
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for HIVEncounterType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="HIVEncounterType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="VisitID" type="{}StringType"/&gt;
 *         &lt;element name="VisitDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="DurationOnArt" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Weight" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="Height" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="BMIMUAC" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="ChildHeight" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="BloodPressure" type="{}StringType" minOccurs="0"/&gt;
 *         &lt;element name="PregnancyBFStatus" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="Pregnant"/&gt;
 *               &lt;enumeration value="Breastfeeding"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="EDDandPMTCTLink" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="P"/&gt;
 *               &lt;enumeration value="PMTCT"/&gt;
 *               &lt;enumeration value="NP"/&gt;
 *               &lt;enumeration value="NK"/&gt;
 *               &lt;enumeration value="BF"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PatientFamilyPlanningCode" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="FP"/&gt;
 *               &lt;enumeration value="NOFP"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PatientFamilyPlanningMethodCode" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="Condoms"/&gt;
 *               &lt;enumeration value="OralContraceptivePills"/&gt;
 *               &lt;enumeration value="InjectableImplantableHormones"/&gt;
 *               &lt;enumeration value="DiaphragmCervicalCap"/&gt;
 *               &lt;enumeration value="IntrauterineDevice"/&gt;
 *               &lt;enumeration value="VasectomyTubalLigationHysterectomy"/&gt;
 *               &lt;enumeration value="Others"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="FunctionalStatus" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="W"/&gt;
 *               &lt;enumeration value="A"/&gt;
 *               &lt;enumeration value="B"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DisclosureStatus" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="OfferedDisclosure"/&gt;
 *               &lt;enumeration value="AcceptedDisclosure"/&gt;
 *               &lt;enumeration value="CommencedPartialDisclosure)"/&gt;
 *               &lt;enumeration value="CompletedFullDisclosure)"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="WHOClinicalStage" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="1"/&gt;
 *               &lt;enumeration value="2"/&gt;
 *               &lt;enumeration value="3"/&gt;
 *               &lt;enumeration value="4"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="TBStatus" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="1"/&gt;
 *               &lt;enumeration value="2"/&gt;
 *               &lt;enumeration value="3"/&gt;
 *               &lt;enumeration value="4"/&gt;
 *               &lt;enumeration value="5"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CryptococcalStatus" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="NotScreened"/&gt;
 *               &lt;enumeration value="ScreenedForCryptococcusAg"/&gt;
 *               &lt;enumeration value="CrAgNegative"/&gt;
 *               &lt;enumeration value="CrAgPositive"/&gt;
 *               &lt;enumeration value="CSFCrAgNegativeCommencedOnPreEmptiveTherapy"/&gt;
 *               &lt;enumeration value="DiagnosedWithCryptococcalMeningitis"/&gt;
 *               &lt;enumeration value="CommencedTreatmentForCryptococcalMeningitis"/&gt;
 *               &lt;enumeration value="CompletedTreatmentForCryptococcalMeningitis"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CervicalCancerScreeningStatus" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="NotOrdered"/&gt;
 *               &lt;enumeration value="OrderedYetToScreen"/&gt;
 *               &lt;enumeration value="ScreenedNegative"/&gt;
 *               &lt;enumeration value="ScreenedPositiveYetToTreat"/&gt;
 *               &lt;enumeration value="ScreenedPositiveAndTreated"/&gt;
 *               &lt;enumeration value="ScreenedPositiveAndReferred"/&gt;
 *               &lt;enumeration value="ScreenedPositiveAndDeclinedTreatment"/&gt;
 *               &lt;enumeration value="SuspiciousForCancer"/&gt;
 *               &lt;enumeration value="OtherFindings"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CervicalTreatmentProvided" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="CR"/&gt;
 *               &lt;enumeration value="TA"/&gt;
 *               &lt;enumeration value="LE"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="HepatitisStatus" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="HepatitisBNegative"/&gt;
 *               &lt;enumeration value="HepatitisBPositive"/&gt;
 *               &lt;enumeration value="HepatitisCNegative"/&gt;
 *               &lt;enumeration value="HepatitisCPositive"/&gt;
 *               &lt;enumeration value="HepatitisBTreatment"/&gt;
 *               &lt;enumeration value="HepatitisCTreatment"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="OtherOIOtherProblems" type="{}CodeType" minOccurs="0"/&gt;
 *         &lt;element name="NotedSideEffects" type="{}CodeType" minOccurs="0"/&gt;
 *         &lt;element name="DSDStatusCode" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="FBM1"/&gt;
 *               &lt;enumeration value="FBM2"/&gt;
 *               &lt;enumeration value="FBM3"/&gt;
 *               &lt;enumeration value="FBM4"/&gt;
 *               &lt;enumeration value="FBM5"/&gt;
 *               &lt;enumeration value="FBM6"/&gt;
 *               &lt;enumeration value="CBM1"/&gt;
 *               &lt;enumeration value="CBM2"/&gt;
 *               &lt;enumeration value="CBM3"/&gt;
 *               &lt;enumeration value="CBM4"/&gt;
 *               &lt;enumeration value="CBM5"/&gt;
 *               &lt;enumeration value="CBM6"/&gt;
 *               &lt;enumeration value="CBM7"/&gt;
 *               &lt;enumeration value="CBM8"/&gt;
 *               &lt;enumeration value="CBM9"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DateDevolved" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="ARVDrugRegimen" type="{}RegimenCodedSimpleType" minOccurs="0"/&gt;
 *         &lt;element name="ARVDrugAdherence" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="G"/&gt;
 *               &lt;enumeration value="F"/&gt;
 *               &lt;enumeration value="P"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="WhyPoorFairARVDrugAdherence" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="1"/&gt;
 *               &lt;enumeration value="2"/&gt;
 *               &lt;enumeration value="3"/&gt;
 *               &lt;enumeration value="4"/&gt;
 *               &lt;enumeration value="5"/&gt;
 *               &lt;enumeration value="6"/&gt;
 *               &lt;enumeration value="7"/&gt;
 *               &lt;enumeration value="8"/&gt;
 *               &lt;enumeration value="9"/&gt;
 *               &lt;enumeration value="10"/&gt;
 *               &lt;enumeration value="11"/&gt;
 *               &lt;enumeration value="12"/&gt;
 *               &lt;enumeration value="13"/&gt;
 *               &lt;enumeration value="14"/&gt;
 *               &lt;enumeration value="15"/&gt;
 *               &lt;enumeration value="16"/&gt;
 *               &lt;enumeration value="17"/&gt;
 *               &lt;enumeration value="18"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CotrimoxazoleDose" type="{}CodedSimpleType" minOccurs="0"/&gt;
 *         &lt;element name="CotrimoxazoleCode" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="SixH"/&gt;
 *               &lt;enumeration value="ThreeHP"/&gt;
 *               &lt;enumeration value="ThreeHR"/&gt;
 *               &lt;enumeration value="QTIP"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CotrimoxazoleAdherence" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="G"/&gt;
 *               &lt;enumeration value="F"/&gt;
 *               &lt;enumeration value="P"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="WhyPoorFairCotrimoxazoleDrugAdherence" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="1"/&gt;
 *               &lt;enumeration value="2"/&gt;
 *               &lt;enumeration value="3"/&gt;
 *               &lt;enumeration value="4"/&gt;
 *               &lt;enumeration value="5"/&gt;
 *               &lt;enumeration value="6"/&gt;
 *               &lt;enumeration value="7"/&gt;
 *               &lt;enumeration value="8"/&gt;
 *               &lt;enumeration value="9"/&gt;
 *               &lt;enumeration value="10"/&gt;
 *               &lt;enumeration value="11"/&gt;
 *               &lt;enumeration value="12"/&gt;
 *               &lt;enumeration value="13"/&gt;
 *               &lt;enumeration value="14"/&gt;
 *               &lt;enumeration value="15"/&gt;
 *               &lt;enumeration value="16"/&gt;
 *               &lt;enumeration value="17"/&gt;
 *               &lt;enumeration value="18"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="INHDose" type="{}CodedSimpleType" minOccurs="0"/&gt;
 *         &lt;element name="INHAdherence" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="G"/&gt;
 *               &lt;enumeration value="F"/&gt;
 *               &lt;enumeration value="P"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="WhyPoorFairINHDrugAdherence" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="1"/&gt;
 *               &lt;enumeration value="2"/&gt;
 *               &lt;enumeration value="3"/&gt;
 *               &lt;enumeration value="4"/&gt;
 *               &lt;enumeration value="5"/&gt;
 *               &lt;enumeration value="6"/&gt;
 *               &lt;enumeration value="7"/&gt;
 *               &lt;enumeration value="8"/&gt;
 *               &lt;enumeration value="9"/&gt;
 *               &lt;enumeration value="10"/&gt;
 *               &lt;enumeration value="11"/&gt;
 *               &lt;enumeration value="12"/&gt;
 *               &lt;enumeration value="13"/&gt;
 *               &lt;enumeration value="14"/&gt;
 *               &lt;enumeration value="15"/&gt;
 *               &lt;enumeration value="16"/&gt;
 *               &lt;enumeration value="17"/&gt;
 *               &lt;enumeration value="18"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CD4" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="CD4TestDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="ReasonForRegimenSwitchSubs" type="{}CodeType" minOccurs="0"/&gt;
 *         &lt;element name="PrescribedRegimenInitialIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="PrescribedRegimenCurrentIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="TypeOfPreviousExposureCode" type="{}CodeType" minOccurs="0"/&gt;
 *         &lt;element name="PoorAdherenceIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="ReasonForPoorAdherence" type="{}CodeType" minOccurs="0"/&gt;
 *         &lt;element name="ReasonRegimenEndedCode" type="{}CodeType" minOccurs="0"/&gt;
 *         &lt;element name="SubstitutionIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="SwitchIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="NextAppointmentDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="StoppedRegimen" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="DateStoppedRegimen" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="ReasonForStoppedRegimen" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="1"/&gt;
 *               &lt;enumeration value="2"/&gt;
 *               &lt;enumeration value="3"/&gt;
 *               &lt;enumeration value="4"/&gt;
 *               &lt;enumeration value="5"/&gt;
 *               &lt;enumeration value="6"/&gt;
 *               &lt;enumeration value="7"/&gt;
 *               &lt;enumeration value="8"/&gt;
 *               &lt;enumeration value="9"/&gt;
 *               &lt;enumeration value="10"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="MethodofTBDiagnosis" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="M1"/&gt;
 *               &lt;enumeration value="M2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="TPTMedication" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="SixH"/&gt;
 *               &lt;enumeration value="ThreeHP"/&gt;
 *               &lt;enumeration value="ThreeHR"/&gt;
 *               &lt;enumeration value="OneHP"/&gt;
 *               &lt;enumeration value="Other"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="TPTDose" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TPTAdherenceCode" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="G"/&gt;
 *               &lt;enumeration value="F"/&gt;
 *               &lt;enumeration value="P"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="OtherDrugsPrescribed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="VLResult" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="VLIndication" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="Targeted"/&gt;
 *               &lt;enumeration value="Routine"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="EACCode" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="None"/&gt;
 *               &lt;enumeration value="EAC1"/&gt;
 *               &lt;enumeration value="EAC2"/&gt;
 *               &lt;enumeration value="EAC3"/&gt;
 *               &lt;enumeration value="EACAdditional"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="RandomBloodSugar" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="OtherTestsDone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ConsultHospitaliseRefer" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="Consult"/&gt;
 *               &lt;enumeration value="Hospitalise"/&gt;
 *               &lt;enumeration value="Referred"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="HealthInsuranceCode" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="None"/&gt;
 *               &lt;enumeration value="NHIA"/&gt;
 *               &lt;enumeration value="BHCPF"/&gt;
 *               &lt;enumeration value="SHIA"/&gt;
 *               &lt;enumeration value="HMO"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HIVEncounterType", propOrder = {
        "visitID",
        "visitDate",
        "durationOnArt",
        "weight",
        "height",
        "bmimuac",
        "childHeight",
        "bloodPressure",
        "pregnancyBFStatus",
        "edDandPMTCTLink",
        "patientFamilyPlanningCode",
        "patientFamilyPlanningMethodCode",
        "functionalStatus",
        "disclosureStatus",
        "whoClinicalStage",
        "tbStatus",
        "cryptococcalStatus",
        "cervicalCancerScreeningStatus",
        "cervicalTreatmentProvided",
        "hepatitisStatus",
        "otherOIOtherProblems",
        "notedSideEffects",
        "dsdStatusCode",
        "dateDevolved",
        "arvDrugRegimen",
        "arvDrugAdherence",
        "whyPoorFairARVDrugAdherence",
        "cotrimoxazoleDose",
        "cotrimoxazoleCode",
        "cotrimoxazoleAdherence",
        "whyPoorFairCotrimoxazoleDrugAdherence",
        "inhDose",
        "inhAdherence",
        "whyPoorFairINHDrugAdherence",
        "cd4",
        "cd4TestDate",
        "reasonForRegimenSwitchSubs",
        "prescribedRegimenInitialIndicator",
        "prescribedRegimenCurrentIndicator",
        "typeOfPreviousExposureCode",
        "poorAdherenceIndicator",
        "reasonForPoorAdherence",
        "reasonRegimenEndedCode",
        "substitutionIndicator",
        "switchIndicator",
        "nextAppointmentDate",
        "stoppedRegimen",
        "dateStoppedRegimen",
        "reasonForStoppedRegimen",
        "methodofTBDiagnosis",
        "tptMedication",
        "tptDose",
        "tptAdherenceCode",
        "otherDrugsPrescribed",
        "vlResult",
        "vlIndication",
        "eacCode",
        "randomBloodSugar",
        "otherTestsDone",
        "consultHospitaliseRefer",
        "healthInsuranceCode"
})
public class HIVEncounterType {

    @XmlElement(name = "VisitID", required = true)
    protected String visitID;
    @XmlElement(name = "VisitDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar visitDate;
    @XmlElement(name = "DurationOnArt")
    protected Integer durationOnArt;
    @XmlElement(name = "Weight") // new
    protected Integer weight;
    @XmlElement(name = "Height")  // new
    protected Integer height;
    @XmlElement(name = "BMIMUAC")  // new
    protected BigDecimal bmimuac;
    @XmlElement(name = "ChildHeight")
    protected Integer childHeight;
    @XmlElement(name = "BloodPressure")
    protected String bloodPressure;
    @XmlElement(name = "PregnancyBFStatus")  // new
    protected String pregnancyBFStatus;
    @XmlElement(name = "EDDandPMTCTLink")
    protected String edDandPMTCTLink;
    @XmlElement(name = "PatientFamilyPlanningCode")
    protected String patientFamilyPlanningCode;
    @XmlElement(name = "PatientFamilyPlanningMethodCode")
    protected String patientFamilyPlanningMethodCode;
    @XmlElement(name = "FunctionalStatus")
    protected String functionalStatus;
    @XmlElement(name = "DisclosureStatus")  // new
    protected String disclosureStatus;
    @XmlElement(name = "WHOClinicalStage")
    protected String whoClinicalStage;
    @XmlElement(name = "TBStatus")
    protected String tbStatus;
    @XmlElement(name = "CryptococcalStatus")  // new
    protected String cryptococcalStatus;
    @XmlElement(name = "CervicalCancerScreeningStatus")  // new
    protected String cervicalCancerScreeningStatus;
    @XmlElement(name = "CervicalTreatmentProvided")  // new
    protected String cervicalTreatmentProvided;
    @XmlElement(name = "HepatitisStatus")  // new
    protected String hepatitisStatus;
    @XmlElement(name = "OtherOIOtherProblems")
    protected String otherOIOtherProblems;
    @XmlElement(name = "NotedSideEffects")
    protected String notedSideEffects;
    @XmlElement(name = "DSDStatusCode")  // new
    protected String dsdStatusCode;
    @XmlElement(name = "DateDevolved")  // new
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateDevolved;
    @XmlElement(name = "ARVDrugRegimen")
    protected RegimenCodedSimpleType arvDrugRegimen; // track this
    @XmlElement(name = "ARVDrugAdherence")
    protected String arvDrugAdherence;
    @XmlElement(name = "WhyPoorFairARVDrugAdherence")
    protected String whyPoorFairARVDrugAdherence;
    @XmlElement(name = "CotrimoxazoleDose")
    protected CodedSimpleType cotrimoxazoleDose; // track this
    @XmlElement(name = "CotrimoxazoleCode")
    protected String cotrimoxazoleCode; // track this
    @XmlElement(name = "CotrimoxazoleAdherence")
    protected String cotrimoxazoleAdherence; // track this
    @XmlElement(name = "WhyPoorFairCotrimoxazoleDrugAdherence")
    protected String whyPoorFairCotrimoxazoleDrugAdherence; // track this
    @XmlElement(name = "INHDose")
    protected CodedSimpleType inhDose; // track this
    @XmlElement(name = "INHAdherence")
    protected String inhAdherence;
    @XmlElement(name = "WhyPoorFairINHDrugAdherence")
    protected String whyPoorFairINHDrugAdherence;
    @XmlElement(name = "CD4")
    protected Integer cd4;
    @XmlElement(name = "CD4TestDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar cd4TestDate;
    @XmlElement(name = "ReasonForRegimenSwitchSubs")
    protected String reasonForRegimenSwitchSubs;
    @XmlElement(name = "PrescribedRegimenInitialIndicator")
    protected Boolean prescribedRegimenInitialIndicator;
    @XmlElement(name = "PrescribedRegimenCurrentIndicator")
    protected Boolean prescribedRegimenCurrentIndicator;
    @XmlElement(name = "TypeOfPreviousExposureCode")
    protected String typeOfPreviousExposureCode;
    @XmlElement(name = "PoorAdherenceIndicator")
    protected Boolean poorAdherenceIndicator;
    @XmlElement(name = "ReasonForPoorAdherence")
    protected String reasonForPoorAdherence;
    @XmlElement(name = "ReasonRegimenEndedCode")
    protected String reasonRegimenEndedCode;
    @XmlElement(name = "SubstitutionIndicator")
    protected Boolean substitutionIndicator;
    @XmlElement(name = "SwitchIndicator")
    protected Boolean switchIndicator;
    @XmlElement(name = "NextAppointmentDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar nextAppointmentDate;
    @XmlElement(name = "StoppedRegimen")
    protected Boolean stoppedRegimen;  // new
    @XmlElement(name = "DateStoppedRegimen")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateStoppedRegimen;  // new
    @XmlElement(name = "ReasonForStoppedRegimen")
    protected String reasonForStoppedRegimen;  // new
    @XmlElement(name = "MethodofTBDiagnosis")
    protected String methodofTBDiagnosis;  // new
    @XmlElement(name = "TPTMedication")
    protected String tptMedication;  // new
    @XmlElement(name = "TPTDose")
    protected String tptDose;  // new
    @XmlElement(name = "TPTAdherenceCode")
    protected String tptAdherenceCode;  // new
    @XmlElement(name = "OtherDrugsPrescribed")
    protected String otherDrugsPrescribed;  // new
    @XmlElement(name = "VLResult")
    protected Integer vlResult;  // new
    @XmlElement(name = "VLIndication")
    protected String vlIndication;  // new
    @XmlElement(name = "EACCode")
    protected String eacCode;  // new
    @XmlElement(name = "RandomBloodSugar")
    protected BigDecimal randomBloodSugar;  // new
    @XmlElement(name = "OtherTestsDone")
    protected String otherTestsDone;  // new
    @XmlElement(name = "ConsultHospitaliseRefer")
    protected String consultHospitaliseRefer;  // new
    @XmlElement(name = "HealthInsuranceCode")
    protected String healthInsuranceCode;  // new

    /**
     * Gets the value of the visitID property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVisitID() {
        return visitID;
    }

    /**
     * Sets the value of the visitID property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVisitID(String value) {
        this.visitID = value;
    }

    /**
     * Gets the value of the visitDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getVisitDate() {
        return visitDate;
    }

    /**
     * Sets the value of the visitDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setVisitDate(XMLGregorianCalendar value) {
        this.visitDate = value;
    }

    /**
     * Gets the value of the durationOnArt property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getDurationOnArt() {
        return durationOnArt;
    }

    /**
     * Sets the value of the durationOnArt property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setDurationOnArt(Integer value) {
        this.durationOnArt = value;
    }

    /**
     * Gets the value of the weight property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setWeight(Integer value) {
        this.weight = value;
    }

    /**
     * Gets the value of the height property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setHeight(Integer value) {
        this.height = value;
    }

    /**
     * Gets the value of the bmimuac property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getBMIMUAC() {
        return bmimuac;
    }

    /**
     * Sets the value of the bmimuac property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setBMIMUAC(BigDecimal value) {
        this.bmimuac = value;
    }

    /**
     * Gets the value of the childHeight property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getChildHeight() {
        return childHeight;
    }

    /**
     * Sets the value of the childHeight property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setChildHeight(Integer value) {
        this.childHeight = value;
    }

    /**
     * Gets the value of the bloodPressure property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBloodPressure() {
        return bloodPressure;
    }

    /**
     * Sets the value of the bloodPressure property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBloodPressure(String value) {
        this.bloodPressure = value;
    }

    /**
     * Gets the value of the pregnancyBFStatus property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPregnancyBFStatus() {
        return pregnancyBFStatus;
    }

    /**
     * Sets the value of the pregnancyBFStatus property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPregnancyBFStatus(String value) {
        this.pregnancyBFStatus = value;
    }

    /**
     * Gets the value of the edDandPMTCTLink property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEDDandPMTCTLink() {
        return edDandPMTCTLink;
    }

    /**
     * Sets the value of the edDandPMTCTLink property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEDDandPMTCTLink(String value) {
        this.edDandPMTCTLink = value;
    }

    /**
     * Gets the value of the patientFamilyPlanningCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPatientFamilyPlanningCode() {
        return patientFamilyPlanningCode;
    }

    /**
     * Sets the value of the patientFamilyPlanningCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPatientFamilyPlanningCode(String value) {
        this.patientFamilyPlanningCode = value;
    }

    /**
     * Gets the value of the patientFamilyPlanningMethodCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPatientFamilyPlanningMethodCode() {
        return patientFamilyPlanningMethodCode;
    }

    /**
     * Sets the value of the patientFamilyPlanningMethodCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPatientFamilyPlanningMethodCode(String value) {
        this.patientFamilyPlanningMethodCode = value;
    }

    /**
     * Gets the value of the functionalStatus property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFunctionalStatus() {
        return functionalStatus;
    }

    /**
     * Sets the value of the functionalStatus property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFunctionalStatus(String value) {
        this.functionalStatus = value;
    }

    /**
     * Gets the value of the disclosureStatus property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDisclosureStatus() {
        return disclosureStatus;
    }

    /**
     * Sets the value of the disclosureStatus property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDisclosureStatus(String value) {
        this.disclosureStatus = value;
    }

    /**
     * Gets the value of the whoClinicalStage property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getWHOClinicalStage() {
        return whoClinicalStage;
    }

    /**
     * Sets the value of the whoClinicalStage property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setWHOClinicalStage(String value) {
        this.whoClinicalStage = value;
    }

    /**
     * Gets the value of the tbStatus property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTBStatus() {
        return tbStatus;
    }

    /**
     * Sets the value of the tbStatus property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTBStatus(String value) {
        this.tbStatus = value;
    }

    /**
     * Gets the value of the cryptococcalStatus property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCryptococcalStatus() {
        return cryptococcalStatus;
    }

    /**
     * Sets the value of the cryptococcalStatus property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCryptococcalStatus(String value) {
        this.cryptococcalStatus = value;
    }

    /**
     * Gets the value of the cervicalCancerScreeningStatus property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCervicalCancerScreeningStatus() {
        return cervicalCancerScreeningStatus;
    }

    /**
     * Sets the value of the cervicalCancerScreeningStatus property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCervicalCancerScreeningStatus(String value) {
        this.cervicalCancerScreeningStatus = value;
    }

    /**
     * Gets the value of the cervicalTreatmentProvided property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCervicalTreatmentProvided() {
        return cervicalTreatmentProvided;
    }

    /**
     * Sets the value of the cervicalTreatmentProvided property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCervicalTreatmentProvided(String value) {
        this.cervicalTreatmentProvided = value;
    }

    /**
     * Gets the value of the hepatitisStatus property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHepatitisStatus() {
        return hepatitisStatus;
    }

    /**
     * Sets the value of the hepatitisStatus property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHepatitisStatus(String value) {
        this.hepatitisStatus = value;
    }

    /**
     * Gets the value of the otherOIOtherProblems property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOtherOIOtherProblems() {
        return otherOIOtherProblems;
    }

    /**
     * Sets the value of the otherOIOtherProblems property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOtherOIOtherProblems(String value) {
        this.otherOIOtherProblems = value;
    }

    /**
     * Gets the value of the notedSideEffects property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNotedSideEffects() {
        return notedSideEffects;
    }

    /**
     * Sets the value of the notedSideEffects property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNotedSideEffects(String value) {
        this.notedSideEffects = value;
    }

    /**
     * Gets the value of the dsdStatusCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDSDStatusCode() {
        return dsdStatusCode;
    }

    /**
     * Sets the value of the dsdStatusCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDSDStatusCode(String value) {
        this.dsdStatusCode = value;
    }

    /**
     * Gets the value of the dateDevolved property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDateDevolved() {
        return dateDevolved;
    }

    /**
     * Sets the value of the dateDevolved property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDateDevolved(XMLGregorianCalendar value) {
        this.dateDevolved = value;
    }

    /**
     * Gets the value of the arvDrugRegimen property.
     *
     * @return
     *     possible object is
     *     {@link RegimenCodedSimpleType }
     *
     */
    public RegimenCodedSimpleType getARVDrugRegimen() {
        return arvDrugRegimen;
    }

    /**
     * Sets the value of the arvDrugRegimen property.
     *
     * @param value
     *     allowed object is
     *     {@link RegimenCodedSimpleType }
     *
     */
    public void setARVDrugRegimen(RegimenCodedSimpleType value) {
        this.arvDrugRegimen = value;
    }

    /**
     * Gets the value of the arvDrugAdherence property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getARVDrugAdherence() {
        return arvDrugAdherence;
    }

    /**
     * Sets the value of the arvDrugAdherence property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setARVDrugAdherence(String value) {
        this.arvDrugAdherence = value;
    }

    /**
     * Gets the value of the whyPoorFairARVDrugAdherence property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getWhyPoorFairARVDrugAdherence() {
        return whyPoorFairARVDrugAdherence;
    }

    /**
     * Sets the value of the whyPoorFairARVDrugAdherence property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setWhyPoorFairARVDrugAdherence(String value) {
        this.whyPoorFairARVDrugAdherence = value;
    }

    /**
     * Gets the value of the cotrimoxazoleDose property.
     *
     * @return
     *     possible object is
     *     {@link CodedSimpleType }
     *
     */
    public CodedSimpleType getCotrimoxazoleDose() {
        return cotrimoxazoleDose;
    }

    /**
     * Sets the value of the cotrimoxazoleDose property.
     *
     * @param value
     *     allowed object is
     *     {@link CodedSimpleType }
     *
     */
    public void setCotrimoxazoleDose(CodedSimpleType value) {
        this.cotrimoxazoleDose = value;
    }

    /**
     * Gets the value of the cotrimoxazoleCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCotrimoxazoleCode() {
        return cotrimoxazoleCode;
    }

    /**
     * Sets the value of the cotrimoxazoleCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCotrimoxazoleCode(String value) {
        this.cotrimoxazoleCode = value;
    }

    /**
     * Gets the value of the cotrimoxazoleAdherence property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCotrimoxazoleAdherence() {
        return cotrimoxazoleAdherence;
    }

    /**
     * Sets the value of the cotrimoxazoleAdherence property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCotrimoxazoleAdherence(String value) {
        this.cotrimoxazoleAdherence = value;
    }

    /**
     * Gets the value of the whyPoorFairCotrimoxazoleDrugAdherence property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getWhyPoorFairCotrimoxazoleDrugAdherence() {
        return whyPoorFairCotrimoxazoleDrugAdherence;
    }

    /**
     * Sets the value of the whyPoorFairCotrimoxazoleDrugAdherence property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setWhyPoorFairCotrimoxazoleDrugAdherence(String value) {
        this.whyPoorFairCotrimoxazoleDrugAdherence = value;
    }

    /**
     * Gets the value of the inhDose property.
     *
     * @return
     *     possible object is
     *     {@link CodedSimpleType }
     *
     */
    public CodedSimpleType getINHDose() {
        return inhDose;
    }

    /**
     * Sets the value of the inhDose property.
     *
     * @param value
     *     allowed object is
     *     {@link CodedSimpleType }
     *
     */
    public void setINHDose(CodedSimpleType value) {
        this.inhDose = value;
    }

    /**
     * Gets the value of the inhAdherence property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getINHAdherence() {
        return inhAdherence;
    }

    /**
     * Sets the value of the inhAdherence property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setINHAdherence(String value) {
        this.inhAdherence = value;
    }

    /**
     * Gets the value of the whyPoorFairINHDrugAdherence property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getWhyPoorFairINHDrugAdherence() {
        return whyPoorFairINHDrugAdherence;
    }

    /**
     * Sets the value of the whyPoorFairINHDrugAdherence property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setWhyPoorFairINHDrugAdherence(String value) {
        this.whyPoorFairINHDrugAdherence = value;
    }

    /**
     * Gets the value of the cd4 property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getCD4() {
        return cd4;
    }

    /**
     * Sets the value of the cd4 property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setCD4(Integer value) {
        this.cd4 = value;
    }

    /**
     * Gets the value of the cd4TestDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getCD4TestDate() {
        return cd4TestDate;
    }

    /**
     * Sets the value of the cd4TestDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setCD4TestDate(XMLGregorianCalendar value) {
        this.cd4TestDate = value;
    }

    /**
     * Gets the value of the reasonForRegimenSwitchSubs property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getReasonForRegimenSwitchSubs() {
        return reasonForRegimenSwitchSubs;
    }

    /**
     * Sets the value of the reasonForRegimenSwitchSubs property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setReasonForRegimenSwitchSubs(String value) {
        this.reasonForRegimenSwitchSubs = value;
    }

    /**
     * Gets the value of the prescribedRegimenInitialIndicator property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isPrescribedRegimenInitialIndicator() {
        return prescribedRegimenInitialIndicator;
    }

    /**
     * Sets the value of the prescribedRegimenInitialIndicator property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setPrescribedRegimenInitialIndicator(Boolean value) {
        this.prescribedRegimenInitialIndicator = value;
    }

    /**
     * Gets the value of the prescribedRegimenCurrentIndicator property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isPrescribedRegimenCurrentIndicator() {
        return prescribedRegimenCurrentIndicator;
    }

    /**
     * Sets the value of the prescribedRegimenCurrentIndicator property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setPrescribedRegimenCurrentIndicator(Boolean value) {
        this.prescribedRegimenCurrentIndicator = value;
    }

    /**
     * Gets the value of the typeOfPreviousExposureCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTypeOfPreviousExposureCode() {
        return typeOfPreviousExposureCode;
    }

    /**
     * Sets the value of the typeOfPreviousExposureCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTypeOfPreviousExposureCode(String value) {
        this.typeOfPreviousExposureCode = value;
    }

    /**
     * Gets the value of the poorAdherenceIndicator property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isPoorAdherenceIndicator() {
        return poorAdherenceIndicator;
    }

    /**
     * Sets the value of the poorAdherenceIndicator property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setPoorAdherenceIndicator(Boolean value) {
        this.poorAdherenceIndicator = value;
    }

    /**
     * Gets the value of the reasonForPoorAdherence property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getReasonForPoorAdherence() {
        return reasonForPoorAdherence;
    }

    /**
     * Sets the value of the reasonForPoorAdherence property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setReasonForPoorAdherence(String value) {
        this.reasonForPoorAdherence = value;
    }

    /**
     * Gets the value of the reasonRegimenEndedCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getReasonRegimenEndedCode() {
        return reasonRegimenEndedCode;
    }

    /**
     * Sets the value of the reasonRegimenEndedCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setReasonRegimenEndedCode(String value) {
        this.reasonRegimenEndedCode = value;
    }

    /**
     * Gets the value of the substitutionIndicator property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isSubstitutionIndicator() {
        return substitutionIndicator;
    }

    /**
     * Sets the value of the substitutionIndicator property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setSubstitutionIndicator(Boolean value) {
        this.substitutionIndicator = value;
    }

    /**
     * Gets the value of the switchIndicator property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isSwitchIndicator() {
        return switchIndicator;
    }

    /**
     * Sets the value of the switchIndicator property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setSwitchIndicator(Boolean value) {
        this.switchIndicator = value;
    }

    /**
     * Gets the value of the nextAppointmentDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getNextAppointmentDate() {
        return nextAppointmentDate;
    }

    /**
     * Sets the value of the nextAppointmentDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setNextAppointmentDate(XMLGregorianCalendar value) {
        this.nextAppointmentDate = value;
    }

    /**
     * Gets the value of the stoppedRegimen property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isStoppedRegimen() {
        return stoppedRegimen;
    }

    /**
     * Sets the value of the stoppedRegimen property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setStoppedRegimen(Boolean value) {
        this.stoppedRegimen = value;
    }

    /**
     * Gets the value of the dateStoppedRegimen property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDateStoppedRegimen() {
        return dateStoppedRegimen;
    }

    /**
     * Sets the value of the dateStoppedRegimen property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDateStoppedRegimen(XMLGregorianCalendar value) {
        this.dateStoppedRegimen = value;
    }

    /**
     * Gets the value of the reasonForStoppedRegimen property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getReasonForStoppedRegimen() {
        return reasonForStoppedRegimen;
    }

    /**
     * Sets the value of the reasonForStoppedRegimen property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setReasonForStoppedRegimen(String value) {
        this.reasonForStoppedRegimen = value;
    }

    /**
     * Gets the value of the methodofTBDiagnosis property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMethodofTBDiagnosis() {
        return methodofTBDiagnosis;
    }

    /**
     * Sets the value of the methodofTBDiagnosis property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMethodofTBDiagnosis(String value) {
        this.methodofTBDiagnosis = value;
    }

    /**
     * Gets the value of the tptMedication property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTPTMedication() {
        return tptMedication;
    }

    /**
     * Sets the value of the tptMedication property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTPTMedication(String value) {
        this.tptMedication = value;
    }

    /**
     * Gets the value of the tptDose property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTPTDose() {
        return tptDose;
    }

    /**
     * Sets the value of the tptDose property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTPTDose(String value) {
        this.tptDose = value;
    }

    /**
     * Gets the value of the tptAdherenceCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTPTAdherenceCode() {
        return tptAdherenceCode;
    }

    /**
     * Sets the value of the tptAdherenceCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTPTAdherenceCode(String value) {
        this.tptAdherenceCode = value;
    }

    /**
     * Gets the value of the otherDrugsPrescribed property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOtherDrugsPrescribed() {
        return otherDrugsPrescribed;
    }

    /**
     * Sets the value of the otherDrugsPrescribed property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOtherDrugsPrescribed(String value) {
        this.otherDrugsPrescribed = value;
    }

    /**
     * Gets the value of the vlResult property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getVLResult() {
        return vlResult;
    }

    /**
     * Sets the value of the vlResult property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setVLResult(Integer value) {
        this.vlResult = value;
    }

    /**
     * Gets the value of the vlIndication property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVLIndication() {
        return vlIndication;
    }

    /**
     * Sets the value of the vlIndication property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVLIndication(String value) {
        this.vlIndication = value;
    }

    /**
     * Gets the value of the eacCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEACCode() {
        return eacCode;
    }

    /**
     * Sets the value of the eacCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEACCode(String value) {
        this.eacCode = value;
    }

    /**
     * Gets the value of the randomBloodSugar property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getRandomBloodSugar() {
        return randomBloodSugar;
    }

    /**
     * Sets the value of the randomBloodSugar property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setRandomBloodSugar(BigDecimal value) {
        this.randomBloodSugar = value;
    }

    /**
     * Gets the value of the otherTestsDone property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOtherTestsDone() {
        return otherTestsDone;
    }

    /**
     * Sets the value of the otherTestsDone property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOtherTestsDone(String value) {
        this.otherTestsDone = value;
    }

    /**
     * Gets the value of the consultHospitaliseRefer property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getConsultHospitaliseRefer() {
        return consultHospitaliseRefer;
    }

    /**
     * Sets the value of the consultHospitaliseRefer property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setConsultHospitaliseRefer(String value) {
        this.consultHospitaliseRefer = value;
    }

    /**
     * Gets the value of the healthInsuranceCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHealthInsuranceCode() {
        return healthInsuranceCode;
    }

    /**
     * Sets the value of the healthInsuranceCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHealthInsuranceCode(String value) {
        this.healthInsuranceCode = value;
    }

}
