//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2024.02.02 at 12:49:02 PM WAT
//


package org.lamisplus.modules.ndr.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for MortalityType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="MortalityType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ClientVerification" type="{}ClientVerificationType" minOccurs="0"/&gt;
 *         &lt;element name="VisitID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="VisitDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="ReasonForTracking" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="CoupTest"/&gt;
 *               &lt;enumeration value="MissAppDate"/&gt;
 *               &lt;enumeration value="MissPharmDate"/&gt;
 *               &lt;enumeration value="Others"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="OtherTrackingReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PartnerFullName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AddressofTreatmentSupporter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ContactPhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DateofLastActualContact" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="DateofMissedScheduledAppointment" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="DatePatientContacted" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="NameofPersonWhoAttemptedContact" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ModeofCommunication" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="MobilePhone"/&gt;
 *               &lt;enumeration value="HomeVisit"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PersonContacted" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="Patient"/&gt;
 *               &lt;enumeration value="Guardian"/&gt;
 *               &lt;enumeration value="TreatmentSupporter"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ReasonforDefaulting" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="Sick"/&gt;
 *               &lt;enumeration value="LackofTransport"/&gt;
 *               &lt;enumeration value="PatientForgottoAttendApp"/&gt;
 *               &lt;enumeration value="FeltBetandStopedMed"/&gt;
 *               &lt;enumeration value="NotPermtoLeaveWork"/&gt;
 *               &lt;enumeration value="LostAppCard"/&gt;
 *               &lt;enumeration value="StillHadDrugs"/&gt;
 *               &lt;enumeration value="HerbalTradMeds"/&gt;
 *               &lt;enumeration value="TreatmentSupporter"/&gt;
 *               &lt;enumeration value="OthersSpecify"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="OtherReasonforDefaulting" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PreviousARVExposure" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="Yes"/&gt;
 *               &lt;enumeration value="No"/&gt;
 *               &lt;enumeration value="UNKNOWN"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Discontinued" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="YES"/&gt;
 *               &lt;enumeration value="NO"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DateofTermination" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="ReasonforTermination" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="TransferredOut"/&gt;
 *               &lt;enumeration value="Death"/&gt;
 *               &lt;enumeration value="Discontinued"/&gt;
 *               &lt;enumeration value="TreatmentStop"/&gt;
 *               &lt;enumeration value="SelfTransfer"/&gt;
 *               &lt;enumeration value="DuplicateRecord"/&gt;
 *               &lt;enumeration value="CouldNotVerifyClient"/&gt;
 *               &lt;enumeration value="LTFU"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ReasonforLosttoFollowup" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="DidNotAttempttoTrackPatient"/&gt;
 *               &lt;enumeration value="TrackedbutUnabletoLocate"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DateReturnedtoCare" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="ReffferedFor" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="AdherenceCounseling"/&gt;
 *               &lt;enumeration value="Other"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ReffferedForOther" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DiscontinuedCare" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="ForcedDiscontinuation"/&gt;
 *               &lt;enumeration value="MovedOutofArea"/&gt;
 *               &lt;enumeration value="Other"/&gt;
 *               &lt;enumeration value="SelfDiscontinuation"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DiscontinueCareOtherSpecify" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TransferredOutTo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Death" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="OtherCauseofDeath"/&gt;
 *               &lt;enumeration value="SuspectedARVSideEffect"/&gt;
 *               &lt;enumeration value="SuspectedOpportunisticInfection"/&gt;
 *               &lt;enumeration value="Unknown"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="VACauseofDeath" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="VAAdultCasesofDeath"/&gt;
 *               &lt;enumeration value="VAChildCasesofDeath"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="OtherCauseofDeath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CauseOfDeath" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="AIDS"/&gt;
 *               &lt;enumeration value="DiarrheaDysentery"/&gt;
 *               &lt;enumeration value="Malaria"/&gt;
 *               &lt;enumeration value="Maternal"/&gt;
 *               &lt;enumeration value="OtherInfetiousDiseases"/&gt;
 *               &lt;enumeration value="Pneumonia"/&gt;
 *               &lt;enumeration value="TB"/&gt;
 *               &lt;enumeration value="AcuteMyocardialInfection"/&gt;
 *               &lt;enumeration value="BreastCancer"/&gt;
 *               &lt;enumeration value="ChronicRespiratoryDiseases"/&gt;
 *               &lt;enumeration value="CervicalCancer"/&gt;
 *               &lt;enumeration value="Cirrhosis"/&gt;
 *               &lt;enumeration value="ColorectalCancer"/&gt;
 *               &lt;enumeration value="Diabetes"/&gt;
 *               &lt;enumeration value="EsophagealCancer"/&gt;
 *               &lt;enumeration value="LeukamiaLymphomas"/&gt;
 *               &lt;enumeration value="LungCancer"/&gt;
 *               &lt;enumeration value="OtherCardiovascularDiseases"/&gt;
 *               &lt;enumeration value="OtherNonCommunicableDiseases"/&gt;
 *               &lt;enumeration value="ProstateCancer"/&gt;
 *               &lt;enumeration value="ChronicKidneyDisease"/&gt;
 *               &lt;enumeration value="StomachCancer"/&gt;
 *               &lt;enumeration value="Stroke"/&gt;
 *               &lt;enumeration value="OtherCancers"/&gt;
 *               &lt;enumeration value="BiteofVenomousAnimal"/&gt;
 *               &lt;enumeration value="Drowning"/&gt;
 *               &lt;enumeration value="Falls"/&gt;
 *               &lt;enumeration value="Fires"/&gt;
 *               &lt;enumeration value="Homicide"/&gt;
 *               &lt;enumeration value="OtherInjuries"/&gt;
 *               &lt;enumeration value="AccidentalPoisoning"/&gt;
 *               &lt;enumeration value="RoadTraffic"/&gt;
 *               &lt;enumeration value="SuicideByMultipleMeans"/&gt;
 *               &lt;enumeration value="Encephalitis"/&gt;
 *               &lt;enumeration value="HemorrhagicFever"/&gt;
 *               &lt;enumeration value="Sepsis"/&gt;
 *               &lt;enumeration value="Meningitis"/&gt;
 *               &lt;enumeration value="Measles"/&gt;
 *               &lt;enumeration value="OtherDefinedCausesofChildDeaths"/&gt;
 *               &lt;enumeration value="OtherDigestiveDiseases"/&gt;
 *               &lt;enumeration value="BirthAsphyxia"/&gt;
 *               &lt;enumeration value="CongenitalMalformation"/&gt;
 *               &lt;enumeration value="NeonatalMeningitis"/&gt;
 *               &lt;enumeration value="NeonatalPneumonia"/&gt;
 *               &lt;enumeration value="PretermDelivery"/&gt;
 *               &lt;enumeration value="Stillbirth"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="NameofContactTracer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ContactTrackerSignatureDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MortalityType", propOrder = {
        "clientVerification",
        "visitID",
        "visitDate",
        "reasonForTracking",
        "otherTrackingReason",
        "partnerFullName",
        "addressofTreatmentSupporter",
        "contactPhoneNumber",
        "dateofLastActualContact",
        "dateofMissedScheduledAppointment",
        "datePatientContacted",
        "nameofPersonWhoAttemptedContact",
        "modeofCommunication",
        "personContacted",
        "reasonforDefaulting",
        "otherReasonforDefaulting",
        "previousARVExposure",
        "discontinued",
        "dateofTermination",
        "reasonforTermination",
        "reasonforLosttoFollowup",
        "dateReturnedtoCare",
        "reffferedFor",
        "reffferedForOther",
        "discontinuedCare",
        "discontinueCareOtherSpecify",
        "transferredOutTo",
        "death",
        "vaCauseofDeath",
        "otherCauseofDeath",
        "causeOfDeath",
        "nameofContactTracer",
        "contactTrackerSignatureDate"
})
public class MortalityType {

    @XmlElement(name = "ClientVerification")
    protected ClientVerificationType clientVerification;
    @XmlElement(name = "VisitID", required = true)
    protected String visitID;
    @XmlElement(name = "VisitDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar visitDate;
    @XmlElement(name = "ReasonForTracking")
    protected String reasonForTracking;
    @XmlElement(name = "OtherTrackingReason")
    protected String otherTrackingReason;
    @XmlElement(name = "PartnerFullName")
    protected String partnerFullName;
    @XmlElement(name = "AddressofTreatmentSupporter")
    protected String addressofTreatmentSupporter;
    @XmlElement(name = "ContactPhoneNumber")
    protected String contactPhoneNumber;
    @XmlElement(name = "DateofLastActualContact")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateofLastActualContact;
    @XmlElement(name = "DateofMissedScheduledAppointment")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateofMissedScheduledAppointment;
    @XmlElement(name = "DatePatientContacted")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datePatientContacted;
    @XmlElement(name = "NameofPersonWhoAttemptedContact")
    protected String nameofPersonWhoAttemptedContact;
    @XmlElement(name = "ModeofCommunication")
    protected String modeofCommunication;
    @XmlElement(name = "PersonContacted")
    protected String personContacted;
    @XmlElement(name = "ReasonforDefaulting")
    protected String reasonforDefaulting;
    @XmlElement(name = "OtherReasonforDefaulting")
    protected String otherReasonforDefaulting;
    @XmlElement(name = "PreviousARVExposure")
    protected String previousARVExposure;
    @XmlElement(name = "Discontinued")
    protected String discontinued;
    @XmlElement(name = "DateofTermination")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateofTermination;
    @XmlElement(name = "ReasonforTermination")
    protected String reasonforTermination;
    @XmlElement(name = "ReasonforLosttoFollowup")
    protected String reasonforLosttoFollowup;
    @XmlElement(name = "DateReturnedtoCare")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateReturnedtoCare;
    @XmlElement(name = "ReffferedFor")
    protected String reffferedFor;
    @XmlElement(name = "ReffferedForOther")
    protected String reffferedForOther;
    @XmlElement(name = "DiscontinuedCare")
    protected String discontinuedCare;
    @XmlElement(name = "DiscontinueCareOtherSpecify")
    protected String discontinueCareOtherSpecify;
    @XmlElement(name = "TransferredOutTo")
    protected String transferredOutTo;
    @XmlElement(name = "Death")
    protected String death;
    @XmlElement(name = "VACauseofDeath")
    protected String vaCauseofDeath;
    @XmlElement(name = "OtherCauseofDeath")
    protected String otherCauseofDeath;
    @XmlElement(name = "CauseOfDeath")
    protected String causeOfDeath;
    @XmlElement(name = "NameofContactTracer")
    protected String nameofContactTracer;
    @XmlElement(name = "ContactTrackerSignatureDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar contactTrackerSignatureDate;

    /**
     * Gets the value of the clientVerification property.
     *
     * @return
     *     possible object is
     *     {@link ClientVerificationType }
     *
     */
    public ClientVerificationType getClientVerification() {
        return clientVerification;
    }

    /**
     * Sets the value of the clientVerification property.
     *
     * @param value
     *     allowed object is
     *     {@link ClientVerificationType }
     *
     */
    public void setClientVerification(ClientVerificationType value) {
        this.clientVerification = value;
    }

    /**
     * Gets the value of the visitID property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVisitID() {
        return visitID;
    }

    /**
     * Sets the value of the visitID property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVisitID(String value) {
        this.visitID = value;
    }

    /**
     * Gets the value of the visitDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getVisitDate() {
        return visitDate;
    }

    /**
     * Sets the value of the visitDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setVisitDate(XMLGregorianCalendar value) {
        this.visitDate = value;
    }

    /**
     * Gets the value of the reasonForTracking property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getReasonForTracking() {
        return reasonForTracking;
    }

    /**
     * Sets the value of the reasonForTracking property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setReasonForTracking(String value) {
        this.reasonForTracking = value;
    }

    /**
     * Gets the value of the otherTrackingReason property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOtherTrackingReason() {
        return otherTrackingReason;
    }

    /**
     * Sets the value of the otherTrackingReason property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOtherTrackingReason(String value) {
        this.otherTrackingReason = value;
    }

    /**
     * Gets the value of the partnerFullName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPartnerFullName() {
        return partnerFullName;
    }

    /**
     * Sets the value of the partnerFullName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPartnerFullName(String value) {
        this.partnerFullName = value;
    }

    /**
     * Gets the value of the addressofTreatmentSupporter property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAddressofTreatmentSupporter() {
        return addressofTreatmentSupporter;
    }

    /**
     * Sets the value of the addressofTreatmentSupporter property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAddressofTreatmentSupporter(String value) {
        this.addressofTreatmentSupporter = value;
    }

    /**
     * Gets the value of the contactPhoneNumber property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getContactPhoneNumber() {
        return contactPhoneNumber;
    }

    /**
     * Sets the value of the contactPhoneNumber property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setContactPhoneNumber(String value) {
        this.contactPhoneNumber = value;
    }

    /**
     * Gets the value of the dateofLastActualContact property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDateofLastActualContact() {
        return dateofLastActualContact;
    }

    /**
     * Sets the value of the dateofLastActualContact property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDateofLastActualContact(XMLGregorianCalendar value) {
        this.dateofLastActualContact = value;
    }

    /**
     * Gets the value of the dateofMissedScheduledAppointment property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDateofMissedScheduledAppointment() {
        return dateofMissedScheduledAppointment;
    }

    /**
     * Sets the value of the dateofMissedScheduledAppointment property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDateofMissedScheduledAppointment(XMLGregorianCalendar value) {
        this.dateofMissedScheduledAppointment = value;
    }

    /**
     * Gets the value of the datePatientContacted property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDatePatientContacted() {
        return datePatientContacted;
    }

    /**
     * Sets the value of the datePatientContacted property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDatePatientContacted(XMLGregorianCalendar value) {
        this.datePatientContacted = value;
    }

    /**
     * Gets the value of the nameofPersonWhoAttemptedContact property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNameofPersonWhoAttemptedContact() {
        return nameofPersonWhoAttemptedContact;
    }

    /**
     * Sets the value of the nameofPersonWhoAttemptedContact property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNameofPersonWhoAttemptedContact(String value) {
        this.nameofPersonWhoAttemptedContact = value;
    }

    /**
     * Gets the value of the modeofCommunication property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getModeofCommunication() {
        return modeofCommunication;
    }

    /**
     * Sets the value of the modeofCommunication property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setModeofCommunication(String value) {
        this.modeofCommunication = value;
    }

    /**
     * Gets the value of the personContacted property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPersonContacted() {
        return personContacted;
    }

    /**
     * Sets the value of the personContacted property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPersonContacted(String value) {
        this.personContacted = value;
    }

    /**
     * Gets the value of the reasonforDefaulting property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getReasonforDefaulting() {
        return reasonforDefaulting;
    }

    /**
     * Sets the value of the reasonforDefaulting property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setReasonforDefaulting(String value) {
        this.reasonforDefaulting = value;
    }

    /**
     * Gets the value of the otherReasonforDefaulting property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOtherReasonforDefaulting() {
        return otherReasonforDefaulting;
    }

    /**
     * Sets the value of the otherReasonforDefaulting property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOtherReasonforDefaulting(String value) {
        this.otherReasonforDefaulting = value;
    }

    /**
     * Gets the value of the previousARVExposure property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPreviousARVExposure() {
        return previousARVExposure;
    }

    /**
     * Sets the value of the previousARVExposure property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPreviousARVExposure(String value) {
        this.previousARVExposure = value;
    }

    /**
     * Gets the value of the discontinued property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDiscontinued() {
        return discontinued;
    }

    /**
     * Sets the value of the discontinued property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDiscontinued(String value) {
        this.discontinued = value;
    }

    /**
     * Gets the value of the dateofTermination property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDateofTermination() {
        return dateofTermination;
    }

    /**
     * Sets the value of the dateofTermination property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDateofTermination(XMLGregorianCalendar value) {
        this.dateofTermination = value;
    }

    /**
     * Gets the value of the reasonforTermination property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getReasonforTermination() {
        return reasonforTermination;
    }

    /**
     * Sets the value of the reasonforTermination property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setReasonforTermination(String value) {
        this.reasonforTermination = value;
    }

    /**
     * Gets the value of the reasonforLosttoFollowup property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getReasonforLosttoFollowup() {
        return reasonforLosttoFollowup;
    }

    /**
     * Sets the value of the reasonforLosttoFollowup property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setReasonforLosttoFollowup(String value) {
        this.reasonforLosttoFollowup = value;
    }

    /**
     * Gets the value of the dateReturnedtoCare property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDateReturnedtoCare() {
        return dateReturnedtoCare;
    }

    /**
     * Sets the value of the dateReturnedtoCare property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDateReturnedtoCare(XMLGregorianCalendar value) {
        this.dateReturnedtoCare = value;
    }

    /**
     * Gets the value of the reffferedFor property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getReffferedFor() {
        return reffferedFor;
    }

    /**
     * Sets the value of the reffferedFor property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setReffferedFor(String value) {
        this.reffferedFor = value;
    }

    /**
     * Gets the value of the reffferedForOther property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getReffferedForOther() {
        return reffferedForOther;
    }

    /**
     * Sets the value of the reffferedForOther property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setReffferedForOther(String value) {
        this.reffferedForOther = value;
    }

    /**
     * Gets the value of the discontinuedCare property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDiscontinuedCare() {
        return discontinuedCare;
    }

    /**
     * Sets the value of the discontinuedCare property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDiscontinuedCare(String value) {
        this.discontinuedCare = value;
    }

    /**
     * Gets the value of the discontinueCareOtherSpecify property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDiscontinueCareOtherSpecify() {
        return discontinueCareOtherSpecify;
    }

    /**
     * Sets the value of the discontinueCareOtherSpecify property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDiscontinueCareOtherSpecify(String value) {
        this.discontinueCareOtherSpecify = value;
    }

    /**
     * Gets the value of the transferredOutTo property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTransferredOutTo() {
        return transferredOutTo;
    }

    /**
     * Sets the value of the transferredOutTo property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTransferredOutTo(String value) {
        this.transferredOutTo = value;
    }

    /**
     * Gets the value of the death property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDeath() {
        return death;
    }

    /**
     * Sets the value of the death property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDeath(String value) {
        this.death = value;
    }

    /**
     * Gets the value of the vaCauseofDeath property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVACauseofDeath() {
        return vaCauseofDeath;
    }

    /**
     * Sets the value of the vaCauseofDeath property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVACauseofDeath(String value) {
        this.vaCauseofDeath = value;
    }

    /**
     * Gets the value of the otherCauseofDeath property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOtherCauseofDeath() {
        return otherCauseofDeath;
    }

    /**
     * Sets the value of the otherCauseofDeath property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOtherCauseofDeath(String value) {
        this.otherCauseofDeath = value;
    }

    /**
     * Gets the value of the causeOfDeath property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCauseOfDeath() {
        return causeOfDeath;
    }

    /**
     * Sets the value of the causeOfDeath property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCauseOfDeath(String value) {
        this.causeOfDeath = value;
    }

    /**
     * Gets the value of the nameofContactTracer property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNameofContactTracer() {
        return nameofContactTracer;
    }

    /**
     * Sets the value of the nameofContactTracer property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNameofContactTracer(String value) {
        this.nameofContactTracer = value;
    }

    /**
     * Gets the value of the contactTrackerSignatureDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getContactTrackerSignatureDate() {
        return contactTrackerSignatureDate;
    }

    /**
     * Sets the value of the contactTrackerSignatureDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setContactTrackerSignatureDate(XMLGregorianCalendar value) {
        this.contactTrackerSignatureDate = value;
    }

}
