//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.19 at 12:13:46 PM WAT 
//


package org.lamisplus.modules.ndr.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PartnerInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PartnerInformationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PartnerAge" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PartnerGender" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="Male"/&gt;
 *               &lt;enumeration value="Female"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ContactInformationProvided" type="{}YNCodeType" minOccurs="0"/&gt;
 *         &lt;element name="RelationshipWithIndex" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="WifeHusbandFiance"/&gt;
 *               &lt;enumeration value="Friend"/&gt;
 *               &lt;enumeration value="CoResident"/&gt;
 *               &lt;enumeration value="OccationalPartner"/&gt;
 *               &lt;enumeration value="SexualRelationsPayer"/&gt;
 *               &lt;enumeration value="SexualRelationsPayee"/&gt;
 *               &lt;enumeration value="InjectDrug"/&gt;
 *               &lt;enumeration value="UnknownPartner"/&gt;
 *               &lt;enumeration value="Others"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="SelfTestingKit" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="Yes"/&gt;
 *               &lt;enumeration value="No"/&gt;
 *               &lt;enumeration value="DontKnow"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="HivVerificationTesting" type="{}YNCodeType" minOccurs="0"/&gt;
 *         &lt;element name="PartnerTested" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="Yes"/&gt;
 *               &lt;enumeration value="No"/&gt;
 *               &lt;enumeration value="DontKnow"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PartnerTestedDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="PartnerTestResult" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="Positive"/&gt;
 *               &lt;enumeration value="Negative"/&gt;
 *               &lt;enumeration value="Indeterminate"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PartnerTestedForRecency" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="Yes"/&gt;
 *               &lt;enumeration value="No"/&gt;
 *               &lt;enumeration value="DontKnow"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PartnerRecencyID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PartnerRecencyTestDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="PartnerRecencyResult" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="Recent"/&gt;
 *               &lt;enumeration value="LongTerm"/&gt;
 *               &lt;enumeration value="Invalid"/&gt;
 *               &lt;enumeration value="Negative"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PartnerLinkedToCare" type="{}YNCodeType" minOccurs="0"/&gt;
 *         &lt;element name="DatePartnerLinkedToCare" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="PartnerInitiatedOnART" type="{}YNCodeType" minOccurs="0"/&gt;
 *         &lt;element name="DatePartnerInitiatedOnART" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="PartnerReferredPrEP" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="Yes"/&gt;
 *               &lt;enumeration value="No"/&gt;
 *               &lt;enumeration value="DontKnow"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PartnerInitiatePrEP" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="Yes"/&gt;
 *               &lt;enumeration value="No"/&gt;
 *               &lt;enumeration value="DontKnow"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PartnerScheduledRepeatHIVtest" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="Yes"/&gt;
 *               &lt;enumeration value="No"/&gt;
 *               &lt;enumeration value="DontKnow"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ReturnedForRepeatHIV" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="Yes"/&gt;
 *               &lt;enumeration value="No"/&gt;
 *               &lt;enumeration value="DontKnow"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DatePartnerRepeatHivTest" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="ReasonPartnerNotTested" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="PostiveDiagnosis"/&gt;
 *               &lt;enumeration value="Refused"/&gt;
 *               &lt;enumeration value="NotLocated"/&gt;
 *               &lt;enumeration value="OutsideState"/&gt;
 *               &lt;enumeration value="Deceased"/&gt;
 *               &lt;enumeration value="Others"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PartnerOnART" type="{}YNCodeType" minOccurs="0"/&gt;
 *         &lt;element name="CurrentARTRegimen" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DateOfLatestVL" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="LatestVLResult" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="VLS6Months" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="Yes"/&gt;
 *               &lt;enumeration value="No"/&gt;
 *               &lt;enumeration value="NA"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="EnhancedAdherenceCounselling" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="Yes"/&gt;
 *               &lt;enumeration value="No"/&gt;
 *               &lt;enumeration value="NA"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="SwitchEvaluatedARTRegimen" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="Yes"/&gt;
 *               &lt;enumeration value="No"/&gt;
 *               &lt;enumeration value="NA"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartnerInformationType", propOrder = {
    "partnerAge",
    "partnerGender",
    "contactInformationProvided",
    "relationshipWithIndex",
    "selfTestingKit",
    "hivVerificationTesting",
    "partnerTested",
    "partnerTestedDate",
    "partnerTestResult",
    "partnerTestedForRecency",
    "partnerRecencyID",
    "partnerRecencyTestDate",
    "partnerRecencyResult",
    "partnerLinkedToCare",
    "datePartnerLinkedToCare",
    "partnerInitiatedOnART",
    "datePartnerInitiatedOnART",
    "partnerReferredPrEP",
    "partnerInitiatePrEP",
    "partnerScheduledRepeatHIVtest",
    "returnedForRepeatHIV",
    "datePartnerRepeatHivTest",
    "reasonPartnerNotTested",
    "partnerOnART",
    "currentARTRegimen",
    "dateOfLatestVL",
    "latestVLResult",
    "vls6Months",
    "enhancedAdherenceCounselling",
    "switchEvaluatedARTRegimen"
})
public class PartnerInformationType {

    @XmlElement(name = "PartnerAge")
    protected String partnerAge;
    @XmlElement(name = "PartnerGender")
    protected String partnerGender;
    @XmlElement(name = "ContactInformationProvided")
    @XmlSchemaType(name = "string")
    protected YNCodeType contactInformationProvided;
    @XmlElement(name = "RelationshipWithIndex")
    protected List<String> relationshipWithIndex;
    @XmlElement(name = "SelfTestingKit")
    protected String selfTestingKit;
    @XmlElement(name = "HivVerificationTesting")
    @XmlSchemaType(name = "string")
    protected YNCodeType hivVerificationTesting;
    @XmlElement(name = "PartnerTested")
    protected String partnerTested;
    @XmlElement(name = "PartnerTestedDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar partnerTestedDate;
    @XmlElement(name = "PartnerTestResult")
    protected String partnerTestResult;
    @XmlElement(name = "PartnerTestedForRecency")
    protected String partnerTestedForRecency;
    @XmlElement(name = "PartnerRecencyID")
    protected String partnerRecencyID;
    @XmlElement(name = "PartnerRecencyTestDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar partnerRecencyTestDate;
    @XmlElement(name = "PartnerRecencyResult")
    protected String partnerRecencyResult;
    @XmlElement(name = "PartnerLinkedToCare")
    @XmlSchemaType(name = "string")
    protected YNCodeType partnerLinkedToCare;
    @XmlElement(name = "DatePartnerLinkedToCare")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datePartnerLinkedToCare;
    @XmlElement(name = "PartnerInitiatedOnART")
    @XmlSchemaType(name = "string")
    protected YNCodeType partnerInitiatedOnART;
    @XmlElement(name = "DatePartnerInitiatedOnART")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datePartnerInitiatedOnART;
    @XmlElement(name = "PartnerReferredPrEP")
    protected String partnerReferredPrEP;
    @XmlElement(name = "PartnerInitiatePrEP")
    protected String partnerInitiatePrEP;
    @XmlElement(name = "PartnerScheduledRepeatHIVtest")
    protected String partnerScheduledRepeatHIVtest;
    @XmlElement(name = "ReturnedForRepeatHIV")
    protected String returnedForRepeatHIV;
    @XmlElement(name = "DatePartnerRepeatHivTest")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datePartnerRepeatHivTest;
    @XmlElement(name = "ReasonPartnerNotTested")
    protected String reasonPartnerNotTested;
    @XmlElement(name = "PartnerOnART")
    @XmlSchemaType(name = "string")
    protected YNCodeType partnerOnART;
    @XmlElement(name = "CurrentARTRegimen")
    protected String currentARTRegimen;
    @XmlElement(name = "DateOfLatestVL")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOfLatestVL;
    @XmlElement(name = "LatestVLResult")
    protected Double latestVLResult;
    @XmlElement(name = "VLS6Months")
    protected String vls6Months;
    @XmlElement(name = "EnhancedAdherenceCounselling")
    protected String enhancedAdherenceCounselling;
    @XmlElement(name = "SwitchEvaluatedARTRegimen")
    protected String switchEvaluatedARTRegimen;

    /**
     * Gets the value of the partnerAge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerAge() {
        return partnerAge;
    }

    /**
     * Sets the value of the partnerAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerAge(String value) {
        this.partnerAge = value;
    }

    /**
     * Gets the value of the partnerGender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerGender() {
        return partnerGender;
    }

    /**
     * Sets the value of the partnerGender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerGender(String value) {
        this.partnerGender = value;
    }

    /**
     * Gets the value of the contactInformationProvided property.
     * 
     * @return
     *     possible object is
     *     {@link YNCodeType }
     *     
     */
    public YNCodeType getContactInformationProvided() {
        return contactInformationProvided;
    }

    /**
     * Sets the value of the contactInformationProvided property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNCodeType }
     *     
     */
    public void setContactInformationProvided(YNCodeType value) {
        this.contactInformationProvided = value;
    }

    /**
     * Gets the value of the relationshipWithIndex property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relationshipWithIndex property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelationshipWithIndex().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRelationshipWithIndex() {
        if (relationshipWithIndex == null) {
            relationshipWithIndex = new ArrayList<String>();
        }
        return this.relationshipWithIndex;
    }

    /**
     * Gets the value of the selfTestingKit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelfTestingKit() {
        return selfTestingKit;
    }

    /**
     * Sets the value of the selfTestingKit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelfTestingKit(String value) {
        this.selfTestingKit = value;
    }

    /**
     * Gets the value of the hivVerificationTesting property.
     * 
     * @return
     *     possible object is
     *     {@link YNCodeType }
     *     
     */
    public YNCodeType getHivVerificationTesting() {
        return hivVerificationTesting;
    }

    /**
     * Sets the value of the hivVerificationTesting property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNCodeType }
     *     
     */
    public void setHivVerificationTesting(YNCodeType value) {
        this.hivVerificationTesting = value;
    }

    /**
     * Gets the value of the partnerTested property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerTested() {
        return partnerTested;
    }

    /**
     * Sets the value of the partnerTested property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerTested(String value) {
        this.partnerTested = value;
    }

    /**
     * Gets the value of the partnerTestedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPartnerTestedDate() {
        return partnerTestedDate;
    }

    /**
     * Sets the value of the partnerTestedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPartnerTestedDate(XMLGregorianCalendar value) {
        this.partnerTestedDate = value;
    }

    /**
     * Gets the value of the partnerTestResult property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerTestResult() {
        return partnerTestResult;
    }

    /**
     * Sets the value of the partnerTestResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerTestResult(String value) {
        this.partnerTestResult = value;
    }

    /**
     * Gets the value of the partnerTestedForRecency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerTestedForRecency() {
        return partnerTestedForRecency;
    }

    /**
     * Sets the value of the partnerTestedForRecency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerTestedForRecency(String value) {
        this.partnerTestedForRecency = value;
    }

    /**
     * Gets the value of the partnerRecencyID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerRecencyID() {
        return partnerRecencyID;
    }

    /**
     * Sets the value of the partnerRecencyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerRecencyID(String value) {
        this.partnerRecencyID = value;
    }

    /**
     * Gets the value of the partnerRecencyTestDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPartnerRecencyTestDate() {
        return partnerRecencyTestDate;
    }

    /**
     * Sets the value of the partnerRecencyTestDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPartnerRecencyTestDate(XMLGregorianCalendar value) {
        this.partnerRecencyTestDate = value;
    }

    /**
     * Gets the value of the partnerRecencyResult property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerRecencyResult() {
        return partnerRecencyResult;
    }

    /**
     * Sets the value of the partnerRecencyResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerRecencyResult(String value) {
        this.partnerRecencyResult = value;
    }

    /**
     * Gets the value of the partnerLinkedToCare property.
     * 
     * @return
     *     possible object is
     *     {@link YNCodeType }
     *     
     */
    public YNCodeType getPartnerLinkedToCare() {
        return partnerLinkedToCare;
    }

    /**
     * Sets the value of the partnerLinkedToCare property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNCodeType }
     *     
     */
    public void setPartnerLinkedToCare(YNCodeType value) {
        this.partnerLinkedToCare = value;
    }

    /**
     * Gets the value of the datePartnerLinkedToCare property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatePartnerLinkedToCare() {
        return datePartnerLinkedToCare;
    }

    /**
     * Sets the value of the datePartnerLinkedToCare property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatePartnerLinkedToCare(XMLGregorianCalendar value) {
        this.datePartnerLinkedToCare = value;
    }

    /**
     * Gets the value of the partnerInitiatedOnART property.
     * 
     * @return
     *     possible object is
     *     {@link YNCodeType }
     *     
     */
    public YNCodeType getPartnerInitiatedOnART() {
        return partnerInitiatedOnART;
    }

    /**
     * Sets the value of the partnerInitiatedOnART property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNCodeType }
     *     
     */
    public void setPartnerInitiatedOnART(YNCodeType value) {
        this.partnerInitiatedOnART = value;
    }

    /**
     * Gets the value of the datePartnerInitiatedOnART property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatePartnerInitiatedOnART() {
        return datePartnerInitiatedOnART;
    }

    /**
     * Sets the value of the datePartnerInitiatedOnART property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatePartnerInitiatedOnART(XMLGregorianCalendar value) {
        this.datePartnerInitiatedOnART = value;
    }

    /**
     * Gets the value of the partnerReferredPrEP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerReferredPrEP() {
        return partnerReferredPrEP;
    }

    /**
     * Sets the value of the partnerReferredPrEP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerReferredPrEP(String value) {
        this.partnerReferredPrEP = value;
    }

    /**
     * Gets the value of the partnerInitiatePrEP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerInitiatePrEP() {
        return partnerInitiatePrEP;
    }

    /**
     * Sets the value of the partnerInitiatePrEP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerInitiatePrEP(String value) {
        this.partnerInitiatePrEP = value;
    }

    /**
     * Gets the value of the partnerScheduledRepeatHIVtest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartnerScheduledRepeatHIVtest() {
        return partnerScheduledRepeatHIVtest;
    }

    /**
     * Sets the value of the partnerScheduledRepeatHIVtest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartnerScheduledRepeatHIVtest(String value) {
        this.partnerScheduledRepeatHIVtest = value;
    }

    /**
     * Gets the value of the returnedForRepeatHIV property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnedForRepeatHIV() {
        return returnedForRepeatHIV;
    }

    /**
     * Sets the value of the returnedForRepeatHIV property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnedForRepeatHIV(String value) {
        this.returnedForRepeatHIV = value;
    }

    /**
     * Gets the value of the datePartnerRepeatHivTest property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatePartnerRepeatHivTest() {
        return datePartnerRepeatHivTest;
    }

    /**
     * Sets the value of the datePartnerRepeatHivTest property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatePartnerRepeatHivTest(XMLGregorianCalendar value) {
        this.datePartnerRepeatHivTest = value;
    }

    /**
     * Gets the value of the reasonPartnerNotTested property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonPartnerNotTested() {
        return reasonPartnerNotTested;
    }

    /**
     * Sets the value of the reasonPartnerNotTested property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonPartnerNotTested(String value) {
        this.reasonPartnerNotTested = value;
    }

    /**
     * Gets the value of the partnerOnART property.
     * 
     * @return
     *     possible object is
     *     {@link YNCodeType }
     *     
     */
    public YNCodeType getPartnerOnART() {
        return partnerOnART;
    }

    /**
     * Sets the value of the partnerOnART property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNCodeType }
     *     
     */
    public void setPartnerOnART(YNCodeType value) {
        this.partnerOnART = value;
    }

    /**
     * Gets the value of the currentARTRegimen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentARTRegimen() {
        return currentARTRegimen;
    }

    /**
     * Sets the value of the currentARTRegimen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentARTRegimen(String value) {
        this.currentARTRegimen = value;
    }

    /**
     * Gets the value of the dateOfLatestVL property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfLatestVL() {
        return dateOfLatestVL;
    }

    /**
     * Sets the value of the dateOfLatestVL property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfLatestVL(XMLGregorianCalendar value) {
        this.dateOfLatestVL = value;
    }

    /**
     * Gets the value of the latestVLResult property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLatestVLResult() {
        return latestVLResult;
    }

    /**
     * Sets the value of the latestVLResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLatestVLResult(Double value) {
        this.latestVLResult = value;
    }

    /**
     * Gets the value of the vls6Months property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVLS6Months() {
        return vls6Months;
    }

    /**
     * Sets the value of the vls6Months property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVLS6Months(String value) {
        this.vls6Months = value;
    }

    /**
     * Gets the value of the enhancedAdherenceCounselling property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnhancedAdherenceCounselling() {
        return enhancedAdherenceCounselling;
    }

    /**
     * Sets the value of the enhancedAdherenceCounselling property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnhancedAdherenceCounselling(String value) {
        this.enhancedAdherenceCounselling = value;
    }

    /**
     * Gets the value of the switchEvaluatedARTRegimen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwitchEvaluatedARTRegimen() {
        return switchEvaluatedARTRegimen;
    }

    /**
     * Sets the value of the switchEvaluatedARTRegimen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwitchEvaluatedARTRegimen(String value) {
        this.switchEvaluatedARTRegimen = value;
    }

}
