//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2025.06.30 at 08:35:02 AM WAT
//


package org.lamisplus.modules.ndr.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for RegimenType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RegimenType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="VisitID" type="{}StringType"/&gt;
 *         &lt;element name="VisitDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="PrescribedRegimen" type="{}CodedSimpleType"/&gt;
 *         &lt;element name="NDRRegimenCode" type="{}CodeType"/&gt;
 *         &lt;element name="PrescribedRegimenTypeCode" type="{}CodeType"/&gt;
 *         &lt;element name="PrescribedRegimenLineCode" type="{}CodeType" minOccurs="0"/&gt;
 *         &lt;element name="PrescribedRegimenDuration" type="{}CodeType"/&gt;
 *         &lt;element name="PrescribedRegimenDispensedDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="DateRegimenStarted" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="DateRegimenStartedDD" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="0"/&gt;
 *               &lt;maxLength value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DateRegimenStartedMM" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="0"/&gt;
 *               &lt;maxLength value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DateRegimenStartedYYYY" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="0"/&gt;
 *               &lt;maxLength value="4"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DateRegimenEnded" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="DateRegimenEndedDD" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="0"/&gt;
 *               &lt;maxLength value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DateRegimenEndedMM" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="0"/&gt;
 *               &lt;maxLength value="2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DateRegimenEndedYYYY" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="0"/&gt;
 *               &lt;maxLength value="4"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PillBalance" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="DifferentiatedServiceDelivery" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="DSD1"/&gt;
 *               &lt;enumeration value="DSD2"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Dispensing" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="FD1"/&gt;
 *               &lt;enumeration value="FD2"/&gt;
 *               &lt;enumeration value="FD3"/&gt;
 *               &lt;enumeration value="FBM2"/&gt;
 *               &lt;enumeration value="FBM3"/&gt;
 *               &lt;enumeration value="FBM4"/&gt;
 *               &lt;enumeration value="FBM5"/&gt;
 *               &lt;enumeration value="FBM6"/&gt;
 *               &lt;enumeration value="FBM7"/&gt;
 *               &lt;enumeration value="FBM8"/&gt;
 *               &lt;enumeration value="DDD01"/&gt;
 *               &lt;enumeration value="DDD02"/&gt;
 *               &lt;enumeration value="DDD03"/&gt;
 *               &lt;enumeration value="DDD04"/&gt;
 *               &lt;enumeration value="DDD05"/&gt;
 *               &lt;enumeration value="DDD06"/&gt;
 *               &lt;enumeration value="DDD07"/&gt;
 *               &lt;enumeration value="CBM2"/&gt;
 *               &lt;enumeration value="CBM3"/&gt;
 *               &lt;enumeration value="CBM4"/&gt;
 *               &lt;enumeration value="CBM6"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="MultiMonthDispensing" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{}CodeType"&gt;
 *               &lt;enumeration value="MMD1"/&gt;
 *               &lt;enumeration value="MMD2"/&gt;
 *               &lt;enumeration value="MMD3"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegimenType", propOrder = {
        "visitID",
        "visitDate",
        "prescribedRegimen",
        "prescribedRegimenTypeCode",
        "prescribedRegimenLineCode",
        "prescribedRegimenDuration",
        "prescribedRegimenDispensedDate",
        "dateRegimenStarted",
        "dateRegimenStartedDD",
        "dateRegimenStartedMM",
        "dateRegimenStartedYYYY",
        "dateRegimenEnded",
        "dateRegimenEndedDD",
        "dateRegimenEndedMM",
        "dateRegimenEndedYYYY",
        "pillBalance",
        "differentiatedServiceDelivery",
        "dispensing",
        "multiMonthDispensing"
})
public class RegimenType {

    @XmlElement(name = "VisitID", required = true)
    protected String visitID;
    @XmlElement(name = "VisitDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar visitDate;
    @XmlElement(name = "PrescribedRegimen", required = true)
    protected RegimenCodedSimpleType prescribedRegimen;
//    @XmlElement(name = "NDRRegimenCode", required = true)
//    protected String ndrRegimenCode;
    @XmlElement(name = "PrescribedRegimenTypeCode", required = true)
    protected String prescribedRegimenTypeCode;
    @XmlElement(name = "PrescribedRegimenLineCode")
    protected String prescribedRegimenLineCode;
    @XmlElement(name = "PrescribedRegimenDuration", required = true)
    protected String prescribedRegimenDuration;
    @XmlElement(name = "PrescribedRegimenDispensedDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar prescribedRegimenDispensedDate;
    @XmlElement(name = "DateRegimenStarted")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateRegimenStarted;
    @XmlElement(name = "DateRegimenStartedDD")
    protected String dateRegimenStartedDD;
    @XmlElement(name = "DateRegimenStartedMM")
    protected String dateRegimenStartedMM;
    @XmlElement(name = "DateRegimenStartedYYYY")
    protected String dateRegimenStartedYYYY;
    @XmlElement(name = "DateRegimenEnded")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateRegimenEnded;
    @XmlElement(name = "DateRegimenEndedDD")
    protected String dateRegimenEndedDD;
    @XmlElement(name = "DateRegimenEndedMM")
    protected String dateRegimenEndedMM;
    @XmlElement(name = "DateRegimenEndedYYYY")
    protected String dateRegimenEndedYYYY;
    @XmlElement(name = "PillBalance")
    protected Integer pillBalance;
    @XmlElement(name = "DifferentiatedServiceDelivery")
    protected String differentiatedServiceDelivery;
    @XmlElement(name = "Dispensing")
    protected String dispensing;
    @XmlElement(name = "MultiMonthDispensing")
    protected String multiMonthDispensing;

    /**
     * Gets the value of the visitID property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVisitID() {
        return visitID;
    }

    /**
     * Sets the value of the visitID property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVisitID(String value) {
        this.visitID = value;
    }

    /**
     * Gets the value of the visitDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getVisitDate() {
        return visitDate;
    }

    /**
     * Sets the value of the visitDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setVisitDate(XMLGregorianCalendar value) {
        this.visitDate = value;
    }

    /**
     * Gets the value of the prescribedRegimen property.
     *
     * @return
     *     possible object is
     *     {@link RegimenCodedSimpleType }
     *
     */
    public RegimenCodedSimpleType getPrescribedRegimen() {
        return prescribedRegimen;
    }

    /**
     * Sets the value of the prescribedRegimen property.
     *
     * @param value
     *     allowed object is
     *     {@link RegimenCodedSimpleType }
     *
     */
    public void setPrescribedRegimen(RegimenCodedSimpleType value) {
        this.prescribedRegimen = value;
    }

    /**
     * Gets the value of the prescribedRegimenTypeCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPrescribedRegimenTypeCode() {
        return prescribedRegimenTypeCode;
    }

    /**
     * Sets the value of the prescribedRegimenTypeCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPrescribedRegimenTypeCode(String value) {
        this.prescribedRegimenTypeCode = value;
    }

    /**
     * Gets the value of the prescribedRegimenLineCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPrescribedRegimenLineCode() {
        return prescribedRegimenLineCode;
    }

    /**
     * Sets the value of the prescribedRegimenLineCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPrescribedRegimenLineCode(String value) {
        this.prescribedRegimenLineCode = value;
    }

    /**
     * Gets the value of the prescribedRegimenDuration property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPrescribedRegimenDuration() {
        return prescribedRegimenDuration;
    }

    /**
     * Sets the value of the prescribedRegimenDuration property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPrescribedRegimenDuration(String value) {
        this.prescribedRegimenDuration = value;
    }

    /**
     * Gets the value of the prescribedRegimenDispensedDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getPrescribedRegimenDispensedDate() {
        return prescribedRegimenDispensedDate;
    }

    /**
     * Sets the value of the prescribedRegimenDispensedDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setPrescribedRegimenDispensedDate(XMLGregorianCalendar value) {
        this.prescribedRegimenDispensedDate = value;
    }

    /**
     * Gets the value of the dateRegimenStarted property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDateRegimenStarted() {
        return dateRegimenStarted;
    }

    /**
     * Sets the value of the dateRegimenStarted property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDateRegimenStarted(XMLGregorianCalendar value) {
        this.dateRegimenStarted = value;
    }

    /**
     * Gets the value of the dateRegimenStartedDD property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDateRegimenStartedDD() {
        return dateRegimenStartedDD;
    }

    /**
     * Sets the value of the dateRegimenStartedDD property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDateRegimenStartedDD(String value) {
        this.dateRegimenStartedDD = value;
    }

    /**
     * Gets the value of the dateRegimenStartedMM property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDateRegimenStartedMM() {
        return dateRegimenStartedMM;
    }

    /**
     * Sets the value of the dateRegimenStartedMM property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDateRegimenStartedMM(String value) {
        this.dateRegimenStartedMM = value;
    }

    /**
     * Gets the value of the dateRegimenStartedYYYY property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDateRegimenStartedYYYY() {
        return dateRegimenStartedYYYY;
    }

    /**
     * Sets the value of the dateRegimenStartedYYYY property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDateRegimenStartedYYYY(String value) {
        this.dateRegimenStartedYYYY = value;
    }

    /**
     * Gets the value of the dateRegimenEnded property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDateRegimenEnded() {
        return dateRegimenEnded;
    }

    /**
     * Sets the value of the dateRegimenEnded property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDateRegimenEnded(XMLGregorianCalendar value) {
        this.dateRegimenEnded = value;
    }

    /**
     * Gets the value of the dateRegimenEndedDD property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDateRegimenEndedDD() {
        return dateRegimenEndedDD;
    }

    /**
     * Sets the value of the dateRegimenEndedDD property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDateRegimenEndedDD(String value) {
        this.dateRegimenEndedDD = value;
    }

    /**
     * Gets the value of the dateRegimenEndedMM property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDateRegimenEndedMM() {
        return dateRegimenEndedMM;
    }

    /**
     * Sets the value of the dateRegimenEndedMM property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDateRegimenEndedMM(String value) {
        this.dateRegimenEndedMM = value;
    }

    /**
     * Gets the value of the dateRegimenEndedYYYY property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDateRegimenEndedYYYY() {
        return dateRegimenEndedYYYY;
    }

    /**
     * Sets the value of the dateRegimenEndedYYYY property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDateRegimenEndedYYYY(String value) {
        this.dateRegimenEndedYYYY = value;
    }

    /**
     * Gets the value of the pillBalance property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getPillBalance() {
        return pillBalance;
    }

    /**
     * Sets the value of the pillBalance property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setPillBalance(Integer value) {
        this.pillBalance = value;
    }

    /**
     * Gets the value of the differentiatedServiceDelivery property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDifferentiatedServiceDelivery() {
        return differentiatedServiceDelivery;
    }

    /**
     * Sets the value of the differentiatedServiceDelivery property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDifferentiatedServiceDelivery(String value) {
        this.differentiatedServiceDelivery = value;
    }

    /**
     * Gets the value of the dispensing property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDispensing() {
        return dispensing;
    }

    /**
     * Sets the value of the dispensing property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDispensing(String value) {
        this.dispensing = value;
    }

    /**
     * Gets the value of the multiMonthDispensing property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMultiMonthDispensing() {
        return multiMonthDispensing;
    }

    /**
     * Sets the value of the multiMonthDispensing property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMultiMonthDispensing(String value) {
        this.multiMonthDispensing = value;
    }

}
