//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.14 at 02:58:02 PM WAT 
//


package org.lamisplus.modules.ndr.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RegimenCodedSimpleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegimenCodedSimpleType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Code" type="{}CodeType"/&gt;
 *         &lt;element name="CodeDescTxt" type="{}CodeDescTxtType" minOccurs="0"/&gt;
 *         &lt;element name="NDRCode" type="{}CodeType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegimenCodedSimpleType", propOrder = {
    "code",
    "codeDescTxt",
    "ndrCode"
})
public class RegimenCodedSimpleType {

    @XmlElement(name = "Code", required = true)
    protected String code;
    @XmlElement(name = "CodeDescTxt")
    protected String codeDescTxt;
    @XmlElement(name = "NDRCode", required = true)
    protected String ndrCode;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the codeDescTxt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeDescTxt() {
        return codeDescTxt;
    }

    /**
     * Sets the value of the codeDescTxt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeDescTxt(String value) {
        this.codeDescTxt = value;
    }

    /**
     * Gets the value of the ndrCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNDRCode() {
        return ndrCode;
    }

    /**
     * Sets the value of the ndrCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNDRCode(String value) {
        this.ndrCode = value;
    }

}
