//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.09 at 01:57:11 PM WAT 
//


package org.lamisplus.modules.ndr.schema.redacted;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EmrType"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="NMRS"/&gt;
 *               &lt;enumeration value="LAMISPlus"/&gt;
 *               &lt;enumeration value="VIVA"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="MessageHeader" type="{}MessageHeaderType"/&gt;
 *         &lt;element name="PatientDemographics" type="{}PatientDemographicsType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "emrType",
    "messageHeader",
    "patientDemographics"
})
@XmlRootElement(name = "Container")
public class Container {

    @XmlElement(name = "EmrType", required = true)
    protected String emrType;
    @XmlElement(name = "MessageHeader", required = true)
    protected MessageHeaderType messageHeader;
    @XmlElement(name = "PatientDemographics", required = true)
    protected PatientDemographicsType patientDemographics;

    /**
     * Gets the value of the emrType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmrType() {
        return emrType;
    }

    /**
     * Sets the value of the emrType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmrType(String value) {
        this.emrType = value;
    }

    /**
     * Gets the value of the messageHeader property.
     * 
     * @return
     *     possible object is
     *     {@link MessageHeaderType }
     *     
     */
    public MessageHeaderType getMessageHeader() {
        return messageHeader;
    }

    /**
     * Sets the value of the messageHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageHeaderType }
     *     
     */
    public void setMessageHeader(MessageHeaderType value) {
        this.messageHeader = value;
    }

    /**
     * Gets the value of the patientDemographics property.
     * 
     * @return
     *     possible object is
     *     {@link PatientDemographicsType }
     *     
     */
    public PatientDemographicsType getPatientDemographics() {
        return patientDemographics;
    }

    /**
     * Sets the value of the patientDemographics property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientDemographicsType }
     *     
     */
    public void setPatientDemographics(PatientDemographicsType value) {
        this.patientDemographics = value;
    }

}
